platform :ios, '9.1'

target 'GetStartedSwift' do

  # Pods for GetStartedSwift

  pod 'MyScriptInteractiveInk-UIReferenceImplementation', :path => '../..'
  pod 'DropDown'
  pod 'DGCollectionViewLeftAlignFlowLayout'
  pod 'Alamofire'
  pod ‘TPKeyboardAvoiding’

   end
